### ISSUE TITLE
Impossible de lancer l'application

### ISSUE THREAD

**Issue by CharlyMZK** [Altraya/AndroidCompanion#2]
09-15 14:56:14.888 3423-3423/project.androidcompanion E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: project.androidcompanion, PID: 3423
                                                                        java.lang.RuntimeException: Unable to create application androidcompanion.main.MyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5888)
                                                                            at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                            at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
                                                                            at org.json.JSONTokener.nextValue(JSONTokener.java:94)
                                                                            at org.json.JSONObject.<init>(JSONObject.java:156)
                                                                            at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                            at androidcompanion.main.MyApp.onCreate(MyApp.java:63)
                                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
                                                                            at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by Altraya** [comment]
Done
