### ISSUE TITLE
Crash on Default device menu press

### ISSUE THREAD

**Issue by TerminatorXRobocop** [Altraya/AndroidCompanion#4]
`Process: project.androidcompanion, PID: 23803
                                                                          java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{project.androidcompanion/project.androidcompanion.ConfigurationActivity}: java.lang.IllegalAccessException: void project.androidcompanion.ConfigurationActivity.<init>() is not accessible from java.lang.Class<android.app.Instrumentation>
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                           Caused by: java.lang.IllegalAccessException: void project.androidcompanion.ConfigurationActivity.<init>() is not accessible from java.lang.Class<android.app.Instrumentation>
                                                                              at java.lang.Class.newInstance(Native Method)
                                                                              at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5525) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)`

**Comment by TerminatorXRobocop** [comment]
Just the shitty line
`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{project.androidcompanion/project.androidcompanion.ConfigurationActivity}: java.lang.IllegalAccessException: void project.androidcompanion.ConfigurationActivity.<init>() is not accessible from java.lang.Class<android.app.Instrumentation>`

**Comment by TerminatorXRobocop** [comment]
Fixed np
